export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST'
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS'
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL'

export const USER_UNFOLLOW_REQUEST = 'USER_UNFOLLOW_REQUEST'
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS'
export const USER_UNFOLLOW_FAIL = 'USER_UNFOLLOW_FAIL'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS'
export const USER_INFO_FAIL = 'USER_INFO_FAIL'

export const USER_FOLLOWERS_REQUEST = 'USER_FOLLOWERS_REQUEST'
export const USER_FOLLOWERS_SUCCESS = 'USER_FOLLOWERS_SUCCESS'
export const USER_FOLLOWERS_FAIL = 'USER_FOLLOWERS_FAIL'

export const USER_FOLLOWING_REQUEST = 'USER_FOLLOWING_REQUEST'
export const USER_FOLLOWING_SUCCESS = 'USER_FOLLOWING_SUCCESS'
export const USER_FOLLOWING_FAIL = 'USER_FOLLOWING_FAIL'

export const USER_COLLECTION_REQUEST = 'USER_COLLECTION_REQUEST'
export const USER_COLLECTION_SUCCESS = 'USER_COLLECTION_SUCCESS'
export const USER_COLLECTION_FAIL = 'USER_COLLECTION_FAIL'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'


export const WORDS_LIST_REQUEST = 'WORDS_LIST_REQUEST';
export const WORDS_LIST_SUCCESS = 'WORDS_LIST_SUCCESS';
export const WORDS_LIST_FAIL = 'WORDS_LIST_FAIL';

export const WORDS_BY_TAG_REQUEST = 'WORDS_BY_TAG_REQUEST';
export const WORDS_BY_TAG_SUCCESS = 'WORDS_BY_TAG_SUCCESS';
export const WORDS_BY_TAG_FAIL = 'WORDS_BY_TAG_FAIL';

export const WORDS_BY_SEARCH_REQUEST = 'WORDS_BY_SEARCH_REQUEST';
export const WORDS_BY_SEARCH_SUCCESS = 'WORDS_BY_SEARCH_SUCCESS';
export const WORDS_BY_SEARCH_FAIL = 'WORDS_BY_SEARCH_FAIL';

export const WORDS_BY_CATEGORY_REQUEST = 'WORDS_BY_CATEGORY_REQUEST';
export const WORDS_BY_CATEGORY_SUCCESS = 'WORDS_BY_CATEGORY_SUCCESS';
export const WORDS_BY_CATEGORY_FAIL = 'WORDS_BY_CATEGORY_FAIL';

export const WORDS_BY_AUTHOR_REQUEST = 'WORDS_BY_AUTHOR_REQUEST';
export const WORDS_BY_AUTHOR_SUCCESS = 'WORDS_BY_AUTHOR_SUCCESS';
export const WORDS_BY_AUTHOR_FAIL = 'WORDS_BY_AUTHOR_FAIL';

export const WORD_LIST_REQUEST = 'WORD_LIST_REQUEST';
export const WORD_LIST_SUCCESS = 'WORD_LIST_SUCCESS';
export const WORD_LIST_FAIL = 'WORD_LIST_FAIL';

export const WORD_CREATE_REQUEST = 'WORD_CREATE_REQUEST';
export const WORD_CREATE_SUCCESS = 'WORD_CREATE_SUCCESS';
export const WORD_CREATE_FAIL = 'WORD_CREATE_FAIL';
export const WORD_CREATE_RESET = 'WORD_CREATE_RESET';

export const WORD_UPDATE_REQUEST = 'WORD_UPDATE_REQUEST';
export const WORD_UPDATE_SUCCESS = 'WORD_UPDATE_SUCCESS';
export const WORD_UPDATE_FAIL = 'WORD_UPDATE_FAIL';
export const WORD_UPDATE_RESET = 'WORD_UPDATE_RESET';

export const WORD_DELETE_REQUEST = 'WORD_DELETE_REQUEST';
export const WORD_DELETE_SUCCESS = 'WORD_DELETE_SUCCESS';
export const WORD_DELETE_FAIL = 'WORD_DELETE_FAIL';

export const WORD_DOWNLOAD_REQUEST = 'WORD_DOWNLOAD_REQUEST';
export const WORD_DOWNLOAD_SUCCESS = 'WORD_DOWNLOAD_SUCCESS';
export const WORD_DOWNLOAD_FAIL = 'WORD_DOWNLOAD_FAIL';

export const WORD_VIEW_REQUEST = 'WORD_VIEW_REQUEST';
export const WORD_VIEW_SUCCESS = 'WORD_VIEW_SUCCESS';
export const WORD_VIEW_FAIL = 'WORD_VIEW_FAIL';

export const WORD_LIKE_REQUEST = 'WORD_LIKE_REQUEST';
export const WORD_LIKE_SUCCESS = 'WORD_LIKE_SUCCESS';
export const WORD_LIKE_FAIL = 'WORD_LIKE_FAIL';

export const WORD_UNLIKE_REQUEST = 'WORD_UNLIKE_REQUEST';
export const WORD_UNLIKE_SUCCESS = 'WORD_UNLIKE_SUCCESS';
export const WORD_UNLIKE_FAIL = 'WORD_UNLIKE_FAIL';

export const WORD_COLLECT_REQUEST = 'WORD_COLLECT_REQUEST';
export const WORD_COLLECT_SUCCESS = 'WORD_COLLECT_SUCCESS';
export const WORD_COLLECT_FAIL = 'WORD_COLLECT_FAIL';

export const WORDS_BY_USER_REQUEST = 'WORDS_BY_USER_REQUEST';
export const WORDS_BY_USER_SUCCESS = 'WORDS_BY_USER_SUCCESS';
export const WORDS_BY_USER_FAIL = 'WORDS_BY_USER_FAIL';


export const CATEGORIES_LIST_REQUEST = 'CATEGORIES_LIST_REQUEST';
export const CATEGORIES_LIST_SUCCESS = 'CATEGORIES_LIST_SUCCESS';
export const CATEGORIES_LIST_FAIL = 'CATEGORIES_LIST_FAIL';

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';


export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST';
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS';
export const TAG_LIST_FAIL = 'TAG_LIST_FAIL';

export const TAGS_LIST_REQUEST = 'TAGS_LIST_REQUEST';
export const TAGS_LIST_SUCCESS = 'TAGS_LIST_SUCCESS';
export const TAGS_LIST_FAIL = 'TAGS_LIST_FAIL';


export const AUTHORS_LIST_REQUEST = 'AUTHORS_LIST_REQUEST';
export const AUTHORS_LIST_SUCCESS = 'AUTHORS_LIST_SUCCESS';
export const AUTHORS_LIST_FAIL = 'AUTHORS_LIST_FAIL';

// export const AUTHOR_LIST_REQUEST = 'AUTHOR_LIST_REQUEST';
// export const AUTHOR_LIST_SUCCESS = 'AUTHOR_LIST_SUCCESS';
// export const AUTHOR_LIST_FAIL = 'AUTHOR_LIST_FAIL';

export const AUTHOR_BY_ALPHABET_LIST_REQUEST = 'AUTHOR_BY_ALPHABET_LIST_REQUEST';
export const AUTHOR_BY_ALPHABET_LIST_SUCCESS = 'AUTHOR_BY_ALPHABET_LIST_SUCCESS';
export const AUTHOR_BY_ALPHABET_LIST_FAIL = 'AUTHOR_BY_ALPHABET_LIST_FAIL';

export const AUTHOR_BY_NAME_LIST_REQUEST = 'AUTHOR_BY_NAME_LIST_REQUEST';
export const AUTHOR_BY_NAME_LIST_SUCCESS = 'AUTHOR_BY_NAME_LIST_SUCCESS';
export const AUTHOR_BY_NAME_LIST_FAIL = 'AUTHOR_BY_NAME_LIST_FAIL';

export const AUTHOR_DETAIL_REQUEST = 'AUTHOR_DETAIL_REQUEST';
export const AUTHOR_DETAIL_SUCCESS = 'AUTHOR_DETAIL_SUCCESS';
export const AUTHOR_DETAIL_FAIL = 'AUTHOR_DETAIL_FAIL';

export const AUTHOR_CREATE_REQUEST = 'AUTHOR_CREATE_REQUEST';
export const AUTHOR_CREATE_SUCCESS = 'AUTHOR_CREATE_SUCCESS';
export const AUTHOR_CREATE_FAIL = 'AUTHOR_CREATE_FAIL';
export const AUTHOR_CREATE_RESET = 'AUTHOR_CREATE_RESET';

export const AUTHOR_UPDATE_REQUEST = 'AUTHOR_UPDATE_REQUEST';
export const AUTHOR_UPDATE_SUCCESS = 'AUTHOR_UPDATE_SUCCESS';
export const AUTHOR_UPDATE_FAIL = 'AUTHOR_UPDATE_FAIL';
export const AUTHOR_UPDATE_RESET = 'AUTHOR_UPDATE_RESET';

export const AUTHOR_DELETE_REQUEST = 'AUTHOR_DELETE_REQUEST';
export const AUTHOR_DELETE_SUCCESS = 'AUTHOR_DELETE_SUCCESS';
export const AUTHOR_DELETE_FAIL = 'AUTHOR_DELETE_FAIL';

export const LIKE_LIST_REQUEST = 'LIKE_LIST_REQUEST';
export const LIKE_LIST_SUCCESS = 'LIKE_LIST_SUCCESS';
export const LIKE_LIST_FAIL = 'LIKE_LIST_FAIL';

export const DISLIKE_LIST_REQUEST = 'DISLIKE_LIST_REQUEST';
export const DISLIKE_LIST_SUCCESS = 'DISLIKE_LIST_SUCCESS';
export const DISLIKE_LIST_FAIL = 'DISLIKE_LIST_FAIL';

export const LIKE_CREATE_REQUEST = 'LIKE_CREATE_REQUEST';
export const LIKE_CREATE_SUCCESS = 'LIKE_CREATE_SUCCESS';
export const LIKE_CREATE_FAIL = 'LIKE_CREATE_FAIL';
export const LIKE_CREATE_RESET = 'LIKE_CREATE_RESET';